# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='user',
        ),
        migrations.AddField(
            model_name='trips',
            name='user',
            field=models.ManyToManyField(related_name='trips', to='travel_buddies.Users'),
        ),
    ]
