# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddies', '0002_auto_20170925_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='trips', to='travel_buddies.Users'),
        ),
    ]
