# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddies', '0003_auto_20170925_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='primaryuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='travel_buddies.Users'),
        ),
    ]
